### ISSUE TITLE
On naming of “quantifier expression”

### ISSUE THREAD

**Issue by hsiang-wu** [rodrigodesalvobraz/neuralpp#28]
I was searching for a name for the class of operation of quantifier expression, which should not only be a `Context`/`Expression`, but also contain a property `identity` (as in [identity element](https://en.wikipedia.org/wiki/Identity_element)), so that when the constrain of a quantifier expression is unsatisfiable, it can be automatically evaluated to the `identity` of its `operation`.

When searching for the name, I found the usage of “quantifier” a bit hard to understand for anyone not familiar with Probabilistic Inference Modulo Theories (PIMT), which uses the word “quantifier” in an unusually generalized way. Since “quantifier” is mostly understood to mean either the universal quantifier (“forall”) or the existential quantifier (“exists”) (there are [more edgy ones](https://en.wikipedia.org/wiki/Quantifier_(logic)), not including summation or product). What PIMT calls “quantifier” is usually referred to as [iterated binary operation](https://en.wikipedia.org/wiki/Iterated_binary_operation), which is also a bit long and uncommon.

I found [a mathematicians’ discussion on the topic of wording of iterated binary operation](https://mathoverflow.net/questions/240402/better-word-for-a-general-iterated-binary-operation), where no good replacement was concluded on (they proposed “summation”, “magmatic operation”).

Further, our “quantifier” operation is supposed to be commutative and associative (as defined in the PIMT paper). So technically the set we operate on is a commutative monoid, or even an abelian group (given inversion).

![img](http://xahlee.info/math/i/group-like_structures_2019-07-25_wd7p2.png)

To conclude, I think we have two names to decide:
 a. The class name of “quantifier” operation
 b. The class name of what’s currently “QuantifierExpression”

Some choices of “a” are:
1. QuantifierOperation. We need to explain to the library users that `QuantifierOperation` should be commutative and associative and contains an identity element.
2. CommutativeMonoidOperation/AbelianOperation. The operation class name is more precise; in terms of “CommutativeMonoidOperation” vs “AbelianOperation”, the former is too long, the latter is not that precise if we don’t include an `inverse()` method.
3. CommutativeAndAssociativeOperation (see the picture above). The fact the it has an identity element is not indicated. Also too long and not straightforward.

Some choices of “b” are:
1. QuantifierExpression. We should include some explanation of the “quantifier” definition here.
2. GeneralizedQuantifierExpression. More precise, as we are not altering the definition of quantifier but extending it.
3. IteratedBinaryExpression. But it’s actually more than that because we requires commutativity, associativity and identity element of the operation.
4. AbelianExpression. Too pedantic?

**Comment by CactusWin** [comment]
For "b", I think in your most recent PR (Normalization of quantifier expression), you used `AbelianOperation`. So, I think using `AbelianExpression` will also work.
